Document: gst-sh-mobile
Title: Debian gst-sh-mobile Manual
Author: <insert document author here>
Abstract: This manual describes what gst-sh-mobile is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gst-sh-mobile/gst-sh-mobile.sgml.gz

Format: postscript
Files: /usr/share/doc/gst-sh-mobile/gst-sh-mobile.ps.gz

Format: text
Files: /usr/share/doc/gst-sh-mobile/gst-sh-mobile.text.gz

Format: HTML
Index: /usr/share/doc/gst-sh-mobile/html/index.html
Files: /usr/share/doc/gst-sh-mobile/html/*.html
